### ISSUE TITLE
List goes below viewport height when filled

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-treenode-navigator#1]
The list of the cosmoz-treenode-navigator goes down beyond the screen height if the list is filled with more items than could be viewed on the screen. User cannot reach the bottom nor buttons in the dialog. A workaround is to select something, then use the Tab key and then Enter to get through it.

The failing line is 35 in cosmoz-treenode-navigator.html:
`max-height: var(--cosmoz-treenode-navigator-max-height, 70vh);`

Lowering the viewport height value makes it work as expected:
`max-height: var(--cosmoz-treenode-navigator-max-height, 40vh);`

**Comment by JaySunSyn** [comment]
@plequang can be closed
