### ISSUE TITLE
Restore reset/no-reset functionality

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-treenode-navigator#24]
By default, cosmoz-treenode-navigator-button should have an "X" to allow the user to clear the selection.
Unless `noReset` is set.

This feature does not seem to work any more and should be restored.
Also a demo should be added.

**Comment by JaySunSyn** [comment]
The reset button only displays if a node has been selected.

Do you mean this (cross on the right) one?

![image](https://user-images.githubusercontent.com/5872432/31393776-cccd4200-addc-11e7-8473-4e8529667b0b.png)

**Comment by nomego** [comment]
Oh sorry I'm a bit confused.. thanks!
