### ISSUE TITLE
_getButtonLabel is not called when nodesOnNodePath is undefined 

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/cosmoz-treenode-navigator#25]
_getButtonLabel is not called when nodesOnNodePath is undefined .

This becomes a problem since Neovici/cosmoz-dialog#10 because nodesOnNodePath is undefined until the dialog template is stamped. 
@nomego Should we default `nodesOnNodePath` to null or empty Array ?

**Comment by megheaiulian** [comment]
The ui looks something like this https://www.dropbox.com/s/9f62xplzab3pa88/Screenshot%202017-11-07%2014.33.20.png?dl=0 until the template is stamped.

**Comment by nomego** [comment]
Well since the component is setup as it is, I think we either need:

1. A way to tell cosmoz-dialog to stamp on attach
or
2. Another approach to managing the button label

There's no point in rendering an empty button.

Actually #2 is the better option, we can put a <cosmoz-treenode> in the button and give it the nodePath to render the right text.

**Comment by JaySunSyn** [comment]
Hi, not sure if I get the context of this discussion. May I ask why to hide it?

- Hiding the button makes `buttonTextPlaceholder` = "Select a node" useless.
- It breakes the demo as the button to open the dialog gets hidden.
![image](https://user-images.githubusercontent.com/5872432/33990697-285f6eaa-e0cc-11e7-82a6-e7997b608e1a.png)
 - `_getButtonLabel(nodesOnNodePath, buttonTextPlaceholder)` returns the placeholder if `nodesOnNodePath` is undefined as `buttonTextPlaceholder` is defined.

**Comment by JaySunSyn** [comment]
I think the actual problem arises if `nodesOnNodePath` has undefined values as nodes. 

e.g. `[{name: 'Node 1'}, undefined, {name: 'Node 3'}]`

`_getButtonLabel` as it doesn't do any undefined checks. 

```javascript
return pathParts.map(part => part[this.tree.searchProperty]).join(' / ');
```

We might want to:
- filter out undefined nodes in `_normalizeNodes`
- or handle undefined nodes in `_getButtonLabel`

Also regarding https://github.com/Neovici/cosmoz-frontend/issues/67
