### ISSUE TITLE
Wrong path displayed for search results

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-treenode-navigator#3]
When searching, the path group displayed for a search result can display the wrong path.

**Comment by JaySunSyn** [comment]
Does the demo data [multiRootTree.json](https://raw.githubusercontent.com/Neovici/cosmoz-treenode-navigator/master/demo/data/multiRootTree.json) contain mistakes? The pathLocator of `Company Jsuymojdos` is `1.7`. Shouldn't it be just `7` or do I get it wrong?

**Comment by JockeCK** [comment]
Yeah it contains mistakes, I just copy & pasted quickly and edited a bit when I wanted to test multiple roots instead of generating an new one.  Did not expect my test json to be in use this long honestly.

**Comment by JaySunSyn** [comment]
Ok, thx, I'll correct that and check if it solely resolves the issue..

**Comment by JaySunSyn** [comment]
@plequang can be closed (or further discussed in https://github.com/Neovici/cosmoz-tree)

**Comment by plequang** [comment]
Fixed by PR #6
